### ISSUE TITLE
Need to Improve Documentation

### ISSUE THREAD

**Issue by ItsMeMIHIR** [eventtus/photo-editor#12]
there is older documents please update it.
this is not working
`let photoEditor = UIStoryboard(name: "PhotoEditor", bundle: Bundle(for: PhotoEditorViewController.self)).instantiateViewController(withIdentifier: "PhotoEditorViewController") as! PhotoEditorViewController`

**Comment by mhm-ibrahim** [comment]
@ItsMeMIHIR Updated Already 
Please check now
