### ISSUE TITLE
not compatible with swift 4

### ISSUE THREAD

**Issue by AD-Paladins** [eventtus/photo-editor#35]
I had some problems translating the photo-editor classes to swift 4
At the moment, when i draw in the image the lines fade and start to going up.

**Comment by AD-Paladins** [comment]
sorry for posting on this issue... but i dont get how to contact you:
[your question](https://github.com/ionic-team/ionic-default-resources/issues/1#issuecomment-244320879)
I resolved this problem using [this](https://www.npmjs.com/package/ionic-resources) npm dependency.

That because i dont want to use a pro account. 
Best regards.

**Comment by ehsan-ff** [comment]
Did you find a workaround for this issue?

**Comment by titopalito** [comment]
yeah!

npm i ionic-resources

Try making the resources with this third party resource, it worked for me.

Best regards.

**Comment by AD-Paladins** [comment]
It only occurs in simulator (for me) try to run it in an iphone.
Best regards.
