### ISSUE TITLE
@objc fro selectors needed,

### ISSUE THREAD

**Issue by rajabpour** [eventtus/photo-editor#39]
for ios 11.4 there is 16 error for adding @objc for selectors functions.

**Comment by mhm-ibrahim** [comment]
Please update to the latest release 0.6 and update me :D @rajabpour

**Comment by AkshayNG** [comment]
Still there need @obj references in v0.6 ...

**1. Protocol:**

![screenshot 2019-01-07 at 12 54 17 pm](https://user-images.githubusercontent.com/15035623/50754316-65d13e80-127b-11e9-9308-c7149b5c0466.png)

**2. Properties**:

![screenshot 2019-01-07 at 12 49 48 pm](https://user-images.githubusercontent.com/15035623/50754184-d461cc80-127a-11e9-9263-e8b893fe2713.png)

Please update. Thanks for the cool library :)
