### ISSUE TITLE
Custom toolbar

### ISSUE THREAD

**Issue by rabehssera** [eventtus/photo-editor#8]
Hello

Is it possible to define which elements in the top toolbar are shown and which are hidden ?

**Comment by mhm-ibrahim** [comment]
Sure will update it by tomorrow

**Comment by mhm-ibrahim** [comment]
@rabehssera  Done, check latest updates thanks for your suggestion

**Comment by mhm-ibrahim** [comment]
@rabehssera can you check and close the issue please

**Comment by rabehssera** [comment]
It's amazing.

Thank you so much !
