### ISSUE TITLE
Use of undeclared type 'PhotoEditorViewController'

### ISSUE THREAD

**Issue by Ali-Aqdas** [eventtus/photo-editor#87]
let vc = self.storyboard?.instantiateViewController(identifier: "PhotoEditorViewController") as PhotoEditorViewController

given error  Use of undeclared type 'PhotoEditorViewController'

**Comment by mhm-ibrahim** [comment]
@Ali-Aqdas  
This is how you do it 
``` let photoEditor = PhotoEditorViewController(nibName:"PhotoEditorViewController",bundle: Bundle(for: PhotoEditorViewController.self))```

Please check the example provided for more details

**Comment by Ali-Aqdas** [comment]
@M-Hamed  i did it but it was not working same issue was showing 
> given error Use of undeclared type 'PhotoEditorViewController'

<img width="782" alt="Screenshot 2019-12-12 12 05 33" src="https://user-images.githubusercontent.com/37294680/70690118-d2e52380-1cd7-11ea-8822-b84af106c793.png">

**Comment by mhm-ibrahim** [comment]
Did you `import iOSPhotoEditor`
