### ISSUE TITLE
Cancel share action

### ISSUE THREAD

**Issue by miff** [eventtus/photo-editor#9]
When Share action is canceled, show up the color picker (color circles for text) above bottom toolbar.
Tap share -> Select (TW, FB, Instagram....) -> Cancel
![img_5215](https://user-images.githubusercontent.com/469459/27155155-1a6f3eaa-5158-11e7-987b-e1a966dea4e1.PNG)

**Comment by mhm-ibrahim** [comment]
Check now @miff

**Comment by mhm-ibrahim** [comment]
@miff can you check and close the issue please

**Comment by miff** [comment]
@M-Hamed it's ok now, but instead edited photo, share original.
Sorry for slow response

**Comment by mhm-ibrahim** [comment]
done 👍

**Comment by miff** [comment]
Nice
