### ISSUE TITLE
Saving an image with a gif

### ISSUE THREAD

**Issue by abeticlairon** [eventtus/photo-editor#91]
First of all thank you for this repo! I added Giphy instead of the stickers and am able to add animated gifs to the editor, however, how could I export the final image with the gif sticker. Right now since it's taking a snapshot of the view, the gif cannot be animated, is there another way to do this and keep the gif animation? 

The current conversion function:
`    func toImage() -> UIImage {
        UIGraphicsBeginImageContextWithOptions(self.bounds.size, self.isOpaque, 0.0)
        self.drawHierarchy(in: self.bounds, afterScreenUpdates: false)
        let snapshotImageFromMyView = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return snapshotImageFromMyView!
    }`

**Comment by stephannagel** [comment]
Considered exporting a small video?

**Comment by abeticlairon** [comment]
Yes I've considered that, but have no idea how to accomplish this. Would you be able to assist me?

**Comment by abeticlairon** [comment]
@stephannagel Here’s the current code I have https://stackoverflow.com/questions/62725463/exporting-instagram-snapchat-like-photos-with-gif-stickers-swift-for-ios

**Comment by stephannagel** [comment]
Hi @abeticlairon, Let's see if we can tackle this problem together. Can you share the whole library with me in a private message. No promises of course :)

**Comment by stephannagel** [comment]
@abeticlairon you tried to share the library, but I think the invite is no longer valid. Am I correct?

**Comment by abeticlairon** [comment]
Sending a new one right away! Thank you.

**Comment by stephannagel** [comment]
Ok, its working. I will have a look at the code this weekend. A few deadlines for now :)

**Comment by abeticlairon** [comment]
Thank you so much!

**Comment by abeticlairon** [comment]
Hi @stephannagel after putting information from various StackOverflow threads together, I found a working solution and will post it sometime today! Thank you!

**Comment by stephannagel** [comment]
Hi @abeticlairon great stuff!! Did you go for video or animated gif? I'm very curious what you did :)

**Comment by abeticlairon** [comment]
I went for the video as you suggested, I just updated the repo, thank you!
